[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico
framework = arduino
board_build.core = earlephilhower
lib_deps =
    greiman/SdFat@^2.2.3
build_flags =
    -DUSE_SDIO=0
    -D USE_SPI_ARRAY_TRANSFER=0
board_build.f_cpu = 133000000L
monitor_speed    = 115200
upload_protocol  = picotool
board_build.arduino.earlephilhower.pio_files =
    src/ccd_driver.pio
    ;src/ads8866_driver.pio
