[env:pico]
platform = raspberrypi
board = pico
framework = arduino
monitor_speed = 115200
build_flags =
    -I include
    -Wno-ignored-qualifiers
lib_deps =
    adafruit/RTClib
    adafruit/Adafruit TMP117
    adafruit/Adafruit BusIO