// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------ //
// convst_pulse //
// ------------ //

#define convst_pulse_wrap_target 0
#define convst_pulse_wrap 6
#define convst_pulse_pio_version 0

static const uint16_t convst_pulse_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0xe001, //  1: set    pins, 1
    0xe057, //  2: set    y, 23
    0xe03e, //  3: set    x, 30
    0x0044, //  4: jmp    x--, 4
    0x0083, //  5: jmp    y--, 3
    0xe000, //  6: set    pins, 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program convst_pulse_program = {
    .instructions = convst_pulse_program_instructions,
    .length = 7,
    .origin = -1,
    .pio_version = convst_pulse_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config convst_pulse_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + convst_pulse_wrap_target, offset + convst_pulse_wrap);
    return c;
}
#endif

